import type { Tables } from "@challenge/core";

/** Fixed typed-column encodings used by the private repository mapper. */
export const columns = {
  users: {
    id: "uuid",
    participantSeed: "seed",
    admin: "boolean",
    createdAt: "instant",
    updatedAt: "instant",
  },
  seasons: {
    id: "uuid",
    title: "text",
    description: "text?",
    state: "text",
    featured: "boolean",
    seasonSeed: "seed",
    goals: "json",
    milestones: "json",
    sessionUrl: "text?",
    version: "integer",
    createdAt: "instant",
    updatedAt: "instant",
  },
  enrollments: {
    id: "uuid",
    userId: "uuid",
    seasonId: "uuid",
    participation: "text",
    timezone: "text?",
    currentAttemptId: "uuid?",
    hasCompleted: "boolean",
    version: "integer",
    createdAt: "instant",
    updatedAt: "instant",
  },
  slots: {
    id: "uuid",
    enrollmentId: "uuid",
  },
  attempts: {
    id: "uuid",
    enrollmentId: "uuid",
    sequence: "integer",
    status: "text",
    mode: "text",
    baseSeed: "seed",
    seedVersion: "text",
    initialInputDigest: "seed",
    initialGoals: "json",
    initialMilestones: "json",
    startedAt: "instant",
    sourceVersion: "integer",
    version: "integer",
    createdAt: "instant",
    updatedAt: "instant",
  },
  goals: {
    id: "uuid",
    attemptId: "uuid",
    currentRevisionId: "uuid",
    archived: "boolean",
    createdAt: "instant",
    updatedAt: "instant",
  },
  goal_revisions: {
    id: "uuid",
    goalId: "uuid",
    attemptId: "uuid",
    input: "json",
    archived: "boolean",
    createdAt: "instant",
  },
  milestones: {
    id: "uuid",
    attemptId: "uuid",
    currentRevisionId: "uuid",
    archived: "boolean",
    locked: "boolean",
    createdAt: "instant",
    updatedAt: "instant",
  },
  milestone_revisions: {
    id: "uuid",
    milestoneId: "uuid",
    attemptId: "uuid",
    input: "json",
    archived: "boolean",
    createdAt: "instant",
  },
  reports: {
    id: "uuid",
    attemptId: "uuid",
    reportingDate: "date",
    reportingIndex: "integer",
    body: "text",
    goalValues: "json",
    applicableGoalRevisionIds: "json",
    streakAtReport: "integer",
    selectedPerks: "json",
    milestoneFacts: "json",
    version: "integer",
    createdAt: "instant",
    updatedAt: "instant",
  },
  credits: {
    id: "uuid",
    attemptId: "uuid",
    earningReportId: "uuid",
    ruleVersion: "integer",
    expired: "boolean",
    createdAt: "instant",
  },
  entitlements: {
    id: "uuid",
    enrollmentId: "uuid",
    attemptId: "uuid",
    completedAt: "instant",
    reportingDates: "json",
  },
  grants: {
    id: "uuid",
    userId: "uuid",
    attemptId: "uuid",
    reportId: "uuid?",
    kind: "text",
    tokenHash: "text",
    expiresAt: "instant",
    usedAt: "instant?",
    revokedAt: "instant?",
    createdAt: "instant",
  },
  replays: {
    id: "uuid",
    userId: "uuid",
    command: "text",
    key: "text",
    requestHash: "text",
    resourceId: "uuid",
    version: "integer",
    expiresAt: "instant",
  },
  outbox: {
    id: "uuid",
    type: "text",
    aggregateId: "uuid",
    sourceVersion: "integer",
    occurredAt: "instant",
    publishedAt: "instant?",
    deliveries: "integer",
  },
  audit: {
    id: "uuid",
    actorId: "uuid",
    action: "text",
    aggregateId: "uuid",
    occurredAt: "instant",
  },
} as const satisfies Record<keyof Tables, Record<string, string>>;
